### ISSUE TITLE
NuclideMixture addAgedNuclideByActivity discrepancy

### ISSUE THREAD

**Issue by kevin-servaenergy** [sandialabs/SandiaDecay#6]
Hi I'm noticing a discrepancy when adding a nuclide to mixture using the `NuclideMixture::addAgedNuclideByActivity` method.
I'm assuming that the results should be the same but they are different. The initial nuclide numAtoms appears to be slightly different and the solution nuclide (stable) appears to have no atoms at all.

```
#include "SandiaDecay/SandiaDecay.h"
#include <cstdio>

using namespace SandiaDecay;

int main(int arg, char * argv[]) {
   SandiaDecayDataBase db(argv[1]);
   const Nuclide * n = db.nuclide("Co60");
   const Nuclide * n2 = db.nuclide("Ni60");
   const double act = 10.0f;
   const double time = 10000.0f;

   NuclideMixture mix;
   NuclideMixture mix2;
   mix.addNuclideByActivity(n, act);
   mix2.addAgedNuclideByActivity(n, act, time);
   printf("Mix1: Co60: %lf, Ni60: %lf\n", mix.numAtoms(time, n), mix.numAtoms(time, n2));
   printf("Mix2: Co60: %lf, Ni60: %lf\n", mix2.numAtoms(0.0, n), mix2.numAtoms(0.0, n2));
   return 0;
}
```

Output:
```
Mix1: Co60: 2399736640.899784, Ni60: 99997.916553
Mix2: Co60: 2399836638.816338, Ni60: 0.000000
```

**Comment by wcjohns** [comment]
Hi Kevin,

The number of Co60 atoms for `mix(t=10000)` and `mix2(t=0)` not being the same is expected behavior.
Instead, I would expect `mix.numAtoms(0, n)` and `mix2.numAtoms(0, n)` to be (very close to) the same.
The `NuclideMixture::addAgedNuclideByActivity(...)` function adds a aged nuclide so the parent nuclides activity at the mixtures `t=0` is the activity you specified, but has the progeny in-growth of the age you specified.  

So, for example, if you have a Am241 sample that you know is 20 years old, and you use a detector to measure its current activity to be 1 Mbq (e.g., using the 59 keV line that is made in the decay from Am241 to Np237), but you wanted to know the number of U233 atoms currently in your sample, and then for in a year from now, you could do something like:
```
NuclideMixture mix;
mix.addAgedNuclideByActivity(db.nuclide("Am241"), 1*MBq, 20*year);
cout << "Currently there are " << mix.numAtoms(0,db.nuclide("U233")) << " U233 atoms\n";
cout << "In 1-year there will be " << mix.numAtoms(1*year,db.nuclide("U233")) << " U233 atoms\n";
```


However, you are right that `Mix2` not having any Ni60 atoms at t=0 is probably not what someone using this function should expect.  Your proposed fix for this issue, I think would address this, but it also changes the desired behavior described above.  I generally don't care about stable nuclides for my work, but for others, like yourself, this is something that can be important.  I think using parts of your proposed fix would be a good way to go, but numerical stability needs to be evaluated - and I likely won't get time to do this before taking off for the holidays.


Thank you Kevin,
  -will

**Comment by kevin-servaenergy** [comment]
Hi Will,

Thanks for looking at the issue and the clarification on the intended behavior.  I'll close the PR I submitted in that case since I misunderstood the behavior. The amount of stable nuclides being returned after aging would still be great to have.

Happy holidays,
Kevin

**Comment by wcjohns** [comment]
Commit da642468b6dc582e6ba3c1de10c5c2e12953da9e adds `NuclideMixture::addAgedNuclideByNumAtoms(...)`, which will also tracks the number of stable nuclide atoms in the solution - so if you are interested in stable nuclides as well, please use `NuclideMixture::addAgedNuclideByNumAtoms(...)`, instead of `NuclideMixture::addAgedNuclideByActivity(...)`.
Some commentary with regard to this has been added to the documentation for these functions.

Sorry it took so long for me to get to this!

best regards,
  -will
